version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: never
  prom-check:
    image: quay.io/geekbass/prom-check
    ports:
      - 5000:5000
    env_file:
      - ./tests/prom-check.conf