version: '3.8'

services:
  prometheus:
    container_name: prometheus
    image: quay.io/prometheus/prometheus
    links:
      - prom-check
    ports:
      - 9090:9090
  prom-check:
    container_name: prom-check
    image: quay.io/geekbass/prom-check:0.0.3
    ports:
      - 5000:5000
    env_file:
      - ./tests/prom-check.conf